export const Strings = {
  progressbarTitle: "Debit Card Spending Limit",
  debitCard: "Debit Card",
  availableBalance: "Available Balance",
  topUpAccount: "Top-up account",
  topUpDesc: "Deposit Money to your account to use with card",
  weeeklySpendLimit: "Weekly spending limit",
  weeeklySpendLimitDesc: "Your weekly spendinf limit is $$",
  freezeCard: "Freeze Card",
  freezeCardDesc: "Your Debit card is currently active",
  getANewCard: "Get a new card",
  getANewCardDesc: "This deactivates your current debit card",
  deactivatedCards: "Deactivated cards",
  deactivatedCardsDesc: "Your previously deactivated cards",
  hideCard: "Hide Card Number",
  showCard: "Show Card Number",
  spendingLimit: "Spending limit",
  weeklyCardLimit: "Set a weekly debit card spending limit",
  weeklyCardLimitDesc:
    "Here weekly means the last 7 days - not the calendar week",
  save: "Save",
  dollar5k: "$$ 5,000",
  dollar10k: "$$ 10,000",
  dollar20k: "$$ 20,000",
};
