export const GET_DEBIT_CARD_DETAILS_REQ_START = "GET_DEBIT_CARD_DETAILS_REQ_START";
export const GET_DEBIT_CARD_DETAILS_SUCCESS = "GET_DEBIT_CARD_DETAILS_SUCCESS";
export const GET_DEBIT_CARD_DETAILS_FAILURE = "GET_DEBIT_CARD_DETAILS_FAILURE";
export const SET_CARD_LIMIT = "SET_CARD_LIMIT";